#receta medica
print("informacion para la receta medica")
print("informacion del paciente")
paciente=input("nombre y apellido del paciente")
nacimiento=input("fecha de nacimiento del paciente")
direcion=input("direccion de la clinica")
print("💊info del medicamento💊")
nombre=input("💊nonmbre del medicamento💊")
dosis=input("dosis de uso")
uso=input("uso del medicamento")
turno=input("fecha del proximo turno")
print("📋RECETA MEDICA📋")
print("nombre/apellido del paciente",paciente,)
print("fecha de nacimiento",nacimiento,)
print("debe tomar",dosis,"dosis de medicamento",nombre,"siguiendo las instrucciones",uso,)
print("fecha de proximo turno",turno,)