nom_completo_paciente = input("Ingrese el nombre completo del paciente: ")
fecha_n_paciente = input("Ingrese la fecha de nacimiento del paciente: ")
direccion_clinica = input("Ingrese la dirección de la clínica médica: ")
nom_medicamento = input("Ingrese el nombre del medicamento: ")
dosis_medicamento = input("Ingrese la dosis del medicamento: ")
inst_medicamento = input("Ingrese las instrucciones del medicamento: ")
fecha_prox_turno = input("Ingrese la fecha del próximo turno: ")

print("_________________________________________________________")
print("Nombre completo del paciente: ", nom_completo_paciente)
print("Fecha de nacimiento del paciente: ", fecha_n_paciente)
print("Dirección de la clínica médica: ", direccion_clinica)
print("Nombre del medicamento: ", nom_medicamento)
print("Dosis del medicamento: ", dosis_medicamento)
print("Instrucciones del medicamento: ", inst_medicamento)
print("Próximo turno: ", fecha_prox_turno)
print("_________________________________________________________")